name: brunocarvalhs-android
description: "Stack para construção de aplicações mobile Android"
displayName: "Android"
category: Front-end
source: https://github.com/brunocarvalhs/templates
compatibility:
  - Android
technologies: [ "Kotlin" ]
